# Generated by Django 4.2.27 on 2026-01-03 22:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congress', models.PositiveIntegerField()),
                ('number', models.CharField(choices=[('u', 'UNKNOWN'), ('i', 'INTRODUCED'), ('p1', 'PASSED_CHAMBER_1'), ('p2', 'PASSED_CHAMBER_2'), ('tp', 'TO_PRESIDENT'), ('bl', 'BECOME_LAW')], default=('u', 'UNKNOWN'), max_length=10)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('update_date', models.DateField()),
                ('introduction_date', models.DateField()),
                ('short_summary', models.TextField(blank=True)),
                ('ethics_score', models.FloatField()),
            ],
            options={
                'unique_together': {('number', 'type', 'congress')},
            },
        ),
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamber', models.CharField(choices=[('u', 'UNKNOWN'), ('h', 'HOUSE'), ('s', 'SENATE')], default=('u', 'UNKNOWN'), max_length=10)),
                ('vote_question', models.CharField(max_length=100)),
                ('vote_result', models.CharField(max_length=10)),
                ('nay_count', models.IntegerField(default=0)),
                ('yea_count', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bill')),
            ],
        ),
        migrations.CreateModel(
            name='Legislator',
            fields=[
                ('bioguide_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image_link', models.TextField(blank=True, null=True)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('current_member', models.BooleanField(default=False)),
                ('birth_year', models.IntegerField(blank=True, null=True)),
                ('current_party', models.CharField(choices=[('u', 'UNKNOWN'), ('i', 'INDEPENDENT'), ('o', 'OTHER'), ('r', 'REPUBLICAN'), ('d', 'DEMOCRAT')], default=('u', 'UNKNOWN'), max_length=100)),
                ('state', models.CharField(choices=[('x', 'UNKNOWN'), ('al', 'Alabama'), ('ak', 'Alaska'), ('as', 'American Samoa'), ('az', 'Arizona'), ('ar', 'Arkansas'), ('ca', 'California'), ('co', 'Colorado'), ('ct', 'Connecticut'), ('de', 'Delaware'), ('dc', 'District of Columbia'), ('fl', 'Florida'), ('ga', 'Georgia'), ('gu', 'Guam'), ('hi', 'Hawaii'), ('id', 'Idaho'), ('il', 'Illinois'), ('in', 'Indiana'), ('ia', 'Iowa'), ('ks', 'Kansas'), ('ky', 'Kentucky'), ('la', 'Louisiana'), ('me', 'Maine'), ('md', 'Maryland'), ('ma', 'Massachusetts'), ('mi', 'Michigan'), ('mn', 'Minnesota'), ('ms', 'Mississippi'), ('mo', 'Missouri'), ('mt', 'Montana'), ('ne', 'Nebraska'), ('nv', 'Nevada'), ('nh', 'New Hampshire'), ('nj', 'New Jersey'), ('nm', 'New Mexico'), ('ny', 'New York'), ('nc', 'North Carolina'), ('nd', 'North Dakota'), ('mp', 'Northern Mariana Islands'), ('oh', 'Ohio'), ('ok', 'Oklahoma'), ('or', 'Oregon'), ('pa', 'Pennsylvania'), ('pr', 'Puerto Rico'), ('ri', 'Rhode Island'), ('sc', 'South Carolina'), ('sd', 'South Dakota'), ('tn', 'Tennessee'), ('tx', 'Texas'), ('ut', 'Utah'), ('vt', 'Vermont'), ('va', 'Virginia'), ('vi', 'Virgin Islands'), ('wa', 'Washington'), ('wv', 'West Virginia'), ('wi', 'Wisconsin'), ('wy', 'Wyoming')], default=('x', 'UNKNOWN'), max_length=100)),
                ('state_code', models.CharField(default='', max_length=10)),
                ('district', models.IntegerField(default=-12)),
                ('current_chamber', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_id', models.CharField(max_length=100)),
                ('election_year', models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(1776)])),
                ('office_full', models.CharField(default='', max_length=100)),
                ('other_political_committee_contributions', models.FloatField(default=0)),
                ('individual_itemized_contributions', models.FloatField(default=0)),
                ('individual_unitemized_contributions', models.FloatField(default=0)),
                ('disbursements', models.FloatField(default=0)),
                ('contributions', models.FloatField(default=0)),
                ('bioguide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legislator')),
            ],
            options={
                'unique_together': {('fec_id', 'election_year')},
            },
        ),
        migrations.CreateModel(
            name='VoteCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=10)),
                ('bill_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.billvote')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legislator')),
            ],
            options={
                'unique_together': {('bill_vote', 'legislator')},
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=10)),
                ('contribution_receipt_amount', models.FloatField()),
                ('contribution_receipt_date', models.DateField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'source_name', 'recipient_name', 'contribution_receipt_date')},
            },
        ),
        migrations.CreateModel(
            name='BillSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('political_subject', models.CharField(max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bill')),
            ],
            options={
                'unique_together': {('bill', 'political_subject')},
            },
        ),
        migrations.CreateModel(
            name='BillSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('u', 'UNKNOWN'), ('s', 'SPONSOR'), ('c', 'COSPONSOR')], default=('u', 'UNKNOWN'), max_length=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bill')),
                ('legislator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.legislator')),
            ],
            options={
                'unique_together': {('bill', 'legislator')},
            },
        ),
    ]
