# Generated by Django 4.2.27 on 2026-01-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='campaign',
            new_name='fec_id',
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('fec_id', 'source_name', 'recipient_name', 'contribution_receipt_date')},
        ),
    ]
