# Generated by Django 4.2.27 on 2026-01-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_campaign_donor_fec_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='fec_id',
            new_name='campaign',
        ),
        migrations.AlterUniqueTogether(
            name='donor',
            unique_together={('campaign', 'source_name', 'recipient_name', 'contribution_receipt_date')},
        ),
    ]
