# Generated by Django 4.2.27 on 2026-01-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fec_id_donor_campaign_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='bioguide_id',
            new_name='legislator',
        ),
    ]
